 
package in.nic.pes.lgd.bean;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* AssemblyConstituency generated by hbm2java
*/
@Entity
@Table(name = "assembly_constituency", schema = "public")
public class AssemblyConstituency implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1594628014398910616L;
	private AssemblyConstituencyId id;
	//private ParliamentConstituency parliamentConstituency;
	//private State state;
	private String acNameEnglish;
	private String acNameLocal;
	private Integer eciCode;
	private Date effectiveDate;
	private Date lastupdated;
	private Integer lastupdatedby;
	private Date createdon;
	private long createdby;
	private boolean isactive;
	private boolean isdisturbed;
	private Integer mapConstituencyCode;
	private Integer constituency_replaces;
	//private int stateCode;
	private int acCode;
	private int acVersion;
	private int plc;
	private int alc;
	
	//private int pcVersion;
	public AssemblyConstituency() {
	}
// TODO Remove unused code found by UCDetector
// 	public AssemblyConstituency(AssemblyConstituencyId id,State state,
// 			String acNameEnglish, Date effectiveDate, Date createdon,
// 			long createdby, boolean isactive, boolean isdisturbed) {
// 		this.id = id;
// 		//this.state = state;
// 		//this.parliamentConstituency = parliamentConstituency;
// 		this.acNameEnglish = acNameEnglish;
// 		this.effectiveDate = effectiveDate;
// 		this.createdon = createdon;
// 		this.createdby = createdby;
// 		this.isactive = isactive;
// 		this.isdisturbed = isdisturbed;
// 	}

// TODO Remove unused code found by UCDetector
// 	 public AssemblyConstituency(AssemblyConstituencyId id,State state,
// 			String acNameEnglish, String acNameLocal, Integer eciCode,
// 			Date effectiveDate, Date lastupdated,Integer lastupdatedby, 
// 			Date createdon, long createdby, boolean isactive,
// 			boolean isdisturbed, Integer mapConstituencyCode) {
// 		this.id = id;
// 		//this.state = state;
// 		//this.parliamentConstituency = parliamentConstituency;
// 		this.acNameEnglish = acNameEnglish;
// 		this.acNameLocal = acNameLocal;
// 		this.eciCode = eciCode;
// 		this.effectiveDate = effectiveDate;
// 		this.lastupdated = lastupdated;
// 		this.lastupdatedby = lastupdatedby;
// 		this.createdon = createdon;
// 		this.createdby = createdby;
// 		this.isactive = isactive;
// 		this.isdisturbed = isdisturbed;
// 		this.mapConstituencyCode = mapConstituencyCode;
// 	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "acCode", column = @Column(name = "ac_code", nullable = false)),
			@AttributeOverride(name = "acVersion", column = @Column(name = "ac_version", nullable = false)) })
	public AssemblyConstituencyId getId() {
		return this.id;
	}

	public void setId(AssemblyConstituencyId id) {
		this.id = id;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "pc_code", referencedColumnName = "pc_code", nullable = false),
			@JoinColumn(name = "pc_version", referencedColumnName = "pc_version", nullable = false) 
			})*/
	/*public ParliamentConstituency getParliamentConstituency() {
		return this.parliamentConstituency;
	}*/
	
	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "state_code", referencedColumnName = "state_code", nullable = false),
			@JoinColumn(name = "state_version", referencedColumnName = "state_version", nullable = false) })
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}
*/
	/*public void setParliamentConstituency(
			ParliamentConstituency parliamentConstituency) {
		this.parliamentConstituency = parliamentConstituency;
	}*/

	@Column(name = "ac_name_english", nullable = false, length = 50)
	public String getAcNameEnglish() {
		return this.acNameEnglish;
	}

	public void setAcNameEnglish(String acNameEnglish) {
		this.acNameEnglish = acNameEnglish;
	}

	@Column(name = "ac_name_local", length = 50)
	public String getAcNameLocal() {
		return this.acNameLocal;
	}

	public void setAcNameLocal(String acNameLocal) {
		this.acNameLocal = acNameLocal;
	}

	@Column(name = "eci_code")
	public Integer getEciCode() {
		return this.eciCode;
	}

	public void setEciCode(Integer eciCode) {
		this.eciCode = eciCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "effective_date", nullable = false, length = 35)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdated", length = 35)
	public Date getLastupdated() {
		return this.lastupdated;
	}

	public void setLastupdated(Date lastupdated) {
		this.lastupdated = lastupdated;
	}

	@Column(name = "lastupdatedby")
	public Integer getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(Integer lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 35)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "createdby", nullable = false)
	public long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "isactive", nullable = false)
	public boolean isIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "isdisturbed", nullable = false)
	public boolean isIsdisturbed() {
		return this.isdisturbed;
	}

	public void setIsdisturbed(boolean isdisturbed) {
		this.isdisturbed = isdisturbed;
	}

	@Column(name = "map_attachment_code")
	public Integer getMapConstituencyCode() {
		return this.mapConstituencyCode;
	}

	public void setMapConstituencyCode(Integer mapConstituencyCode) {
		this.mapConstituencyCode = mapConstituencyCode;
	}

	@Column(name = "constituency_replaces")
	public Integer getConstituency_replaces() {
		return constituency_replaces;
	}

	public void setConstituency_replaces(Integer constituency_replaces) {
		this.constituency_replaces = constituency_replaces;
	}
	@Column(name = "ac_code",insertable=false,updatable=false)
	public int getAcCode() {
		return acCode;
	}

	public void setAcCode(int acCode) {
		this.acCode = acCode;
	}
	@Column(name = "ac_version",insertable=false,updatable=false)
	public int getAcVersion() {
		return acVersion;
	}

	public void setAcVersion(int acVersion) {
		this.acVersion = acVersion;
	}
	
	@Column(name = "plc", nullable = false,insertable=false,updatable=false)
	public int getPlc() {
		return plc;
	}
	public void setPlc(int plc) {
		this.plc = plc;
	}
	@Column(name = "alc")
	public int getAlc() {
		return alc;
	}
	public void setAlc(int alc) {
		this.alc = alc;
	}
	
	/*@Column(name = "pc_version", nullable = false,insertable=false,updatable=false)

	public int getPcVersion() {
		return pcVersion;
	}
	public void setPcVersion(int pcVersion) {
		this.pcVersion = pcVersion;
	}*/
}
