/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package in.nic.pes.lgd.bean;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ConfigurationMapLocalbody generated by hbm2java
 */
@Entity
@Table(name = "configuration_map_localbody", schema = "public")
public class ConfigurationMapLocalbody implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7616919582128992759L;
	private int configurationMapLocalbodyCode;
	private int tierSetupCode;
	private String baseUrl;
	private boolean isactive;
	private boolean ismapupload;
	private Date lastupdated;
	private Long lastupdatedby;
	private Date createdon;
	private long createdby;

	public ConfigurationMapLocalbody() {
	}

// TODO Remove unused code found by UCDetector
// 	public ConfigurationMapLocalbody(int configurationMapLocalbodyCode,
// 			int tierSetupCode, boolean isactive, boolean ismapupload,
// 			Date createdon, long createdby) {
// 		this.configurationMapLocalbodyCode = configurationMapLocalbodyCode;
// 		this.tierSetupCode = tierSetupCode;
// 		this.isactive = isactive;
// 		this.ismapupload = ismapupload;
// 		this.createdon = createdon;
// 		this.createdby = createdby;
// 	}

// TODO Remove unused code found by UCDetector
// 	public ConfigurationMapLocalbody(int configurationMapLocalbodyCode,
// 			int tierSetupCode, String baseUrl, boolean isactive,
// 			boolean ismapupload, Date lastupdated, Long lastupdatedby,
// 			Date createdon, long createdby) {
// 		this.configurationMapLocalbodyCode = configurationMapLocalbodyCode;
// 		this.tierSetupCode = tierSetupCode;
// 		this.baseUrl = baseUrl;
// 		this.isactive = isactive;
// 		this.ismapupload = ismapupload;
// 		this.lastupdated = lastupdated;
// 		this.lastupdatedby = lastupdatedby;
// 		this.createdon = createdon;
// 		this.createdby = createdby;
// 	}

	@GenericGenerator
    (name = "sequence", strategy = "sequence", parameters={@Parameter(name="sequence",value="configmapbody")})
	@GeneratedValue(generator = "sequence")
 	@Id	
	@Column(name = "configuration_map_localbody_code", unique = true, nullable = false)
	public int getConfigurationMapLocalbodyCode() {
		return this.configurationMapLocalbodyCode;
	}

	public void setConfigurationMapLocalbodyCode(
			int configurationMapLocalbodyCode) {
		this.configurationMapLocalbodyCode = configurationMapLocalbodyCode;
	}

	@Column(name = "tier_setup_code", nullable = false)
	public int getTierSetupCode() {
		return this.tierSetupCode;
	}

	public void setTierSetupCode(int tierSetupCode) {
		this.tierSetupCode = tierSetupCode;
	}

	@Column(name = "base_url", length = 100)
	public String getBaseUrl() {
		return this.baseUrl;
	}

	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}

	@Column(name = "isactive", nullable = false)
	public boolean isIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "ismapupload", nullable = false)
	public boolean isIsmapupload() {
		return this.ismapupload;
	}

	public void setIsmapupload(boolean ismapupload) {
		this.ismapupload = ismapupload;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "lastupdated", length = 21)
	public Date getLastupdated() {
		return this.lastupdated;
	}

	public void setLastupdated(Date lastupdated) {
		this.lastupdated = lastupdated;
	}

	@Column(name = "lastupdatedby")
	public Long getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(Long lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 35)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "createdby", nullable = false)
	public long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(long createdby) {
		this.createdby = createdby;
	}

}
