/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package in.nic.pes.lgd.bean;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocalbodyWardId generated by hbm2java
 */
@Embeddable
public class LocalbodyWardId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 745167249276940768L;
	private int wardCode;
	private int wardVersion;

	public LocalbodyWardId() {
	}

// TODO Remove unused code found by UCDetector
// 	public LocalbodyWardId(int wardCode, int wardVersion) {
// 		this.wardCode = wardCode;
// 		this.wardVersion = wardVersion;
// 	}
	
     
   // @GeneratedValue(strategy=GenerationType.AUTO)
   /* @GenericGenerator
    (name = "sequence", strategy = "sequence", parameters={@Parameter(name="sequence",value="ward_seq")})*/
   	@Column(name = "ward_code", nullable = false)
	public int getWardCode() {
		return this.wardCode;
	}

	public void setWardCode(int wardCode) {
		this.wardCode = wardCode;
	}

	@Column(name = "ward_version", nullable = false)
	public int getWardVersion() {
		return this.wardVersion;
	}

	public void setWardVersion(int wardVersion) {
		this.wardVersion = wardVersion;
	}
/*
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocalbodyWardId))
			return false;
		LocalbodyWardId castOther = (LocalbodyWardId) other;

		return (this.getWardCode() == castOther.getWardCode())
				&& (this.getWardVersion() == castOther.getWardVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWardCode();
		result = 37 * result + this.getWardVersion();
		return result;
	}*/

}
