package in.nic.pes.lgd.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * OraganizationDesignation generated by hbm2java
 */
@Entity
@Table(name = "oraganization_designation", schema = "public")
public class OrganizationDesignation implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8903333668666135959L;
	private int designationCode;
    private Integer olc;
    //private Organization organization;
    private OrgLocatedAtLevels orgLocatedAtLevels;
    private String designationName;
    private String designationNameLocal;
    private boolean istopdesignation;
    private boolean ismultiple;
    private Integer reportTo;
    private Integer resourceId;
    private boolean isactive;
    private boolean iscontractpermanent;

    @Column(name = "iscontractpermanent", nullable = false)
    public boolean isIscontractpermanent() {
		return iscontractpermanent;
	}

	public void setIscontractpermanent(boolean iscontractpermanent) {
		this.iscontractpermanent = iscontractpermanent;
	}

	@Column(name = "olc") 
    public Integer getOlc() {
		return olc;
	}

	public void setOlc(Integer olc) {
		this.olc = olc;
	}

	public OrganizationDesignation() {
    }

// TODO Remove unused code found by UCDetector
//     public OrganizationDesignation(int designationCode,
//             String designationName,Integer olc,
//             boolean istopdesignation, boolean ismultiple, boolean isactive, boolean iscontractpermanent) 
//     {
//         this.designationCode = designationCode;
//         this.olc=olc;
//         //this.organization = organization;
//         this.designationName = designationName;
//         this.istopdesignation = istopdesignation;
//         this.ismultiple = ismultiple;
//         this.isactive = isactive;
//         this.iscontractpermanent= iscontractpermanent;
//     }

// TODO Remove unused code found by UCDetector
//     public OrganizationDesignation(int designationCode,
//             OrgLocatedAtLevels orgLocatedAtLevels,Integer olc,
//             String designationName, String designationNameLocal,
//             boolean istopdesignation, boolean ismultiple, Integer reportTo,
//             Integer resourceId, boolean isactive,boolean iscontractpermanent) {
//         this.designationCode = designationCode;
//         //this.organization = organization;
//         this.olc=olc;
//         this.orgLocatedAtLevels = orgLocatedAtLevels;
//         this.designationName = designationName;
//         this.designationNameLocal = designationNameLocal;
//         this.istopdesignation = istopdesignation;
//         this.ismultiple = ismultiple;
//         this.reportTo = reportTo;
//         this.resourceId = resourceId;
//         this.isactive = isactive;
//         this.iscontractpermanent= iscontractpermanent;
//     }

	@GenericGenerator(name = "generator", strategy = "increment", parameters = {})
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name = "designation_code", unique = true, nullable = false)
    public int getDesignationCode() {
        return this.designationCode;
    }

    public void setDesignationCode(int designationCode) {
        this.designationCode = designationCode;
    }

  /*  @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "org_code", referencedColumnName = "org_code", nullable = false),
            @JoinColumn(name = "org_version", referencedColumnName = "org_version", nullable = false) })
    public Organization getOrganization() {
        return this.organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
*/
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_located_level_code")
    public OrgLocatedAtLevels getOrgLocatedAtLevels() {
        return this.orgLocatedAtLevels;
    }

    public void setOrgLocatedAtLevels(OrgLocatedAtLevels orgLocatedAtLevels) {
        this.orgLocatedAtLevels = orgLocatedAtLevels;
    }

    @Column(name = "designation_name", nullable = false, length = 50)
    public String getDesignationName() {
        return this.designationName;
    }

    public void setDesignationName(String designationName) {
        this.designationName = designationName;
    }

    @Column(name = "designation_name_local", length = 100)
    public String getDesignationNameLocal() {
        return this.designationNameLocal;
    }

    public void setDesignationNameLocal(String designationNameLocal) {
        this.designationNameLocal = designationNameLocal;
    }

    @Column(name = "istopdesignation", nullable = false)
    public boolean isIstopdesignation() {
        return this.istopdesignation;
    }

    public void setIstopdesignation(boolean istopdesignation) {
        this.istopdesignation = istopdesignation;
    }

    @Column(name = "ismultiple", nullable = false)
    public boolean isIsmultiple() {
        return this.ismultiple;
    }

    public void setIsmultiple(boolean ismultiple) {
        this.ismultiple = ismultiple;
    }

    @Column(name = "report_to")
    public Integer getReportTo() {
        return this.reportTo;
    }

    public void setReportTo(Integer reportTo) {
        this.reportTo = reportTo;
    }

    @Column(name = "resource_id")
    public Integer getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    @Column(name = "isactive", nullable = false)
    public boolean isIsactive() {
        return this.isactive;
    }

    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }

}