// default package
// Generated 6 Dec, 2011 1:24:48 PM by Hibernate Tools 3.4.0.CR1
package in.nic.pes.lgd.bean;

// default package
// Generated Nov 24, 2011 12:27:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParliamentConstituencyId generated by hbm2java
 */
@Embeddable
public class ParliamentConstituencyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6542468286256631510L;
	private int pcCode;
	private int pcVersion;

	public ParliamentConstituencyId() {
	}

	public ParliamentConstituencyId(int pcCode, int pcVersion) {
		this.pcCode = pcCode;
		this.pcVersion = pcVersion;
	}

	@Column(name = "pc_code", nullable = false)
	public int getPcCode() {
		return this.pcCode;
	}

	public void setPcCode(int pcCode) {
		this.pcCode = pcCode;
	}

	@Column(name = "pc_version", nullable = false)
	public int getPcVersion() {
		return this.pcVersion;
	}

	public void setPcVersion(int pcVersion) {
		this.pcVersion = pcVersion;
	}

	public boolean equals(Object other) {
		if ((this == other)){
			return true;
		}	
		if ((other == null)){
			return false;
		}	
		if (!(other instanceof ParliamentConstituencyId)){
			return false;
		}	
		ParliamentConstituencyId castOther = (ParliamentConstituencyId) other;

		return (this.getPcCode() == castOther.getPcCode())
				&& (this.getPcVersion() == castOther.getPcVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPcCode();
		result = 37 * result + this.getPcVersion();
		return result;
	}

}
