/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package in.nic.pes.lgd.bean;

//default package
//Generated Nov 24, 2011 12:27:08 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* ParliamentConstituency generated by hbm2java
*/
@Entity
@Table(name = "parliament_constituency", schema = "public")
public class ParliamentConstituency implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5948036837467789276L;
	private ParliamentConstituencyId id;
	private String pcNameEnglish;
	private String pcNameLocal;
	private Integer eciCode;
	private Date effectiveDate;
	private Date lastupdated;
	//private int lastupdatedby;
	private Date createdon;
	private long createdby;
	private boolean isdisturbed;
	private boolean isactive;
	private Integer mapConstituencyCode;
	private int slc;
	private Integer constituency_replaces;
	private Integer constituency_replacedby;
	 
	private int pcCode;
	private int pcVersion;
	/*private Set<AssemblyConstituency> assemblyConstituencies = new HashSet<AssemblyConstituency>(
			0);
*/
	public ParliamentConstituency() {
	}

// TODO Remove unused code found by UCDetector
// 	public ParliamentConstituency(ParliamentConstituencyId id, 
// 			String pcNameEnglish, Date effectiveDate, Date createdon,
// 			long createdby, boolean isdisturbed, boolean isactive) {
// 		this.id = id;
// 		//this.state = state;
// 		this.pcNameEnglish = pcNameEnglish;
// 		this.effectiveDate = effectiveDate;
// 		this.createdon = createdon;
// 		this.createdby = createdby;
// 		this.isdisturbed = isdisturbed;
// 		this.isactive = isactive;
// 		
// 	}

// TODO Remove unused code found by UCDetector
// 	public ParliamentConstituency(ParliamentConstituencyId id,
// 			String pcNameEnglish, String pcNameLocal, Integer eciCode,
// 			Date effectiveDate, Date lastupdated, 
// 			Date createdon, long createdby, boolean isdisturbed,
// 			boolean isactive, Integer mapConstituencyCode,
// 			Set<AssemblyConstituency> assemblyConstituencies) {
// 		this.id = id;
// 		//this.state = state;
// 		this.pcNameEnglish = pcNameEnglish;
// 		this.pcNameLocal = pcNameLocal;
// 		this.eciCode = eciCode;
// 		this.effectiveDate = effectiveDate;
// 		this.lastupdated = lastupdated;
// 		//this.lastupdatedby = lastupdatedby;
// 		this.createdon = createdon;
// 		this.createdby = createdby;
// 		this.isdisturbed = isdisturbed;
// 		this.isactive = isactive;
// 		this.mapConstituencyCode = mapConstituencyCode;
// 		
// 		 
// 	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pcCode", column = @Column(name = "pc_code", nullable = false)),
			@AttributeOverride(name = "pcVersion", column = @Column(name = "pc_version", nullable = false)) })
	public ParliamentConstituencyId getId() {
		return this.id;
	}

	public void setId(ParliamentConstituencyId id) {
		this.id = id;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "slc", referencedColumnName = "slc", nullable = false)
			@JoinColumn(name = "state_version", referencedColumnName = "state_version", nullable = false)
			//@JoinColumn(name = "isactive", referencedColumnName = "isactive" , nullable = false)
			})*/
	/*public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}*/

	@Column(name = "pc_name_english", nullable = false, length = 50)
	public String getPcNameEnglish() {
		return this.pcNameEnglish;
	}

	public void setPcNameEnglish(String pcNameEnglish) {
		this.pcNameEnglish = pcNameEnglish;
	}

	@Column(name = "pc_name_local", length = 50)
	public String getPcNameLocal() {
		return this.pcNameLocal;
	}

	public void setPcNameLocal(String pcNameLocal) {
		this.pcNameLocal = pcNameLocal;
	}

	@Column(name = "eci_code")
	public Integer getEciCode() {
		return this.eciCode;
	}

	public void setEciCode(Integer eciCode) {
		this.eciCode = eciCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "effective_date", nullable = false, length = 35)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdated", length = 35)
	public Date getLastupdated() {
		return this.lastupdated;
	}

	public void setLastupdated(Date lastupdated) {
		this.lastupdated = lastupdated;
	}

	/*@Column(name = "lastupdatedby")
	public int getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(int lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}*/

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", nullable = false, length = 35)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "createdby", nullable = false)
	public long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(long createdby) {
		this.createdby = createdby;
	}

	@Column(name = "isdisturbed", nullable = false)
	public boolean isIsdisturbed() {
		return this.isdisturbed;
	}

	public void setIsdisturbed(boolean isdisturbed) {
		this.isdisturbed = isdisturbed;
	}

	@Column(name = "isactive", nullable = false,insertable=false,updatable=false)
	public boolean isIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	@Column(name = "map_attachment_code")
	public Integer getMapConstituencyCode() {
		return this.mapConstituencyCode;
	}

	public void setMapConstituencyCode(Integer mapConstituencyCode) {
		this.mapConstituencyCode = mapConstituencyCode;
	}

	
	@Column(name = "constituency_replaces")
	public Integer getConstituency_replaces() {
		return constituency_replaces;
	}

	public void setConstituency_replaces(Integer constituency_replaces) {
		this.constituency_replaces = constituency_replaces;
	}

	@Column(name = "constituency_replacedby")
	public Integer getConstituency_replacedby() {
		return constituency_replacedby;
	}

	public void setConstituency_replacedby(Integer constituency_replacedby) {
		this.constituency_replacedby = constituency_replacedby;
	}

	
	
	@Column(name = "slc",insertable=false,updatable=false)
	public int getSlc() {
		return slc;
	}

	public void setSlc(int slc) {
		this.slc = slc;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "parliamentConstituency")
	public Set<AssemblyConstituency> getAssemblyConstituencies() {
		return this.assemblyConstituencies;
	}

	public void setAssemblyConstituencies(
			Set<AssemblyConstituency> assemblyConstituencies) {
		this.assemblyConstituencies = assemblyConstituencies;
	}*/
	@Column(name = "pc_code",insertable=false,updatable=false)
	public int getPcCode() {
		return pcCode;
	}

	public void setPcCode(int pcCode) {
		this.pcCode = pcCode;
	}
	@Column(name = "pc_version",insertable=false,updatable=false)
	public int getPcVersion() {
		return pcVersion;
	}

	public void setPcVersion(int pcVersion) {
		this.pcVersion = pcVersion;
	}

}
