//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssemblyConstituency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssemblyConstituency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ACCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ACVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="PCVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="EciCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="GovernmentOrderDetails" type="{http://www.ws.lgd.pes.nic.in}GovernmentOrderDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssemblyConstituency", propOrder = {
    "acCode",
    "acVersion",
    "nameEnglish",
    "nameLocal",
    "pcCode",
    "pcVersion",
    "eciCode",
    "governmentOrderDetails"
})
public class AssemblyConstituency { // NO_UCD (use default)

    @XmlElement(name = "ACCode")
    private Integer acCode;
    @XmlElement(name = "ACVersion")
    private Integer acVersion;
    @XmlElement(name = "NameEnglish")
    private String nameEnglish;
    @XmlElement(name = "NameLocal")
    private String nameLocal;
    @XmlElement(name = "PCCode")
    private Integer pcCode;
    @XmlElement(name = "PCVersion")
    private Integer pcVersion;
    @XmlElement(name = "EciCode")
    private Integer eciCode;
    @XmlElement(name = "GovernmentOrderDetails")
    private GovernmentOrderDetails governmentOrderDetails;

    /**
     * Gets the value of the acCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getACCode() {
        return acCode;
    }

    /**
     * Sets the value of the acCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setACCode(Integer value) {
        this.acCode = value;
    }

    /**
     * Gets the value of the acVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getACVersion() {
        return acVersion;
    }

    /**
     * Sets the value of the acVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setACVersion(Integer value) {
        this.acVersion = value;
    }

    /**
     * Gets the value of the nameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEnglish() {
        return nameEnglish;
    }

    /**
     * Sets the value of the nameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEnglish(String value) {
        this.nameEnglish = value;
    }

    /**
     * Gets the value of the nameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLocal() {
        return nameLocal;
    }

    /**
     * Sets the value of the nameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLocal(String value) {
        this.nameLocal = value;
    }

    /**
     * Gets the value of the pcCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPCCode() {
        return pcCode;
    }

    /**
     * Sets the value of the pcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPCCode(Integer value) {
        this.pcCode = value;
    }

    /**
     * Gets the value of the pcVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPCVersion() {
        return pcVersion;
    }

    /**
     * Sets the value of the pcVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPCVersion(Integer value) {
        this.pcVersion = value;
    }

    /**
     * Gets the value of the eciCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEciCode() {
        return eciCode;
    }

    /**
     * Sets the value of the eciCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEciCode(Integer value) {
        this.eciCode = value;
    }

    /**
     * Gets the value of the governmentOrderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public GovernmentOrderDetails getGovernmentOrderDetails() {
        return governmentOrderDetails;
    }

    /**
     * Sets the value of the governmentOrderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public void setGovernmentOrderDetails(GovernmentOrderDetails value) {
        this.governmentOrderDetails = value;
    }

}
