//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type will provide Entire Heirarchy of a particular BLOCK
 *             
 * 
 * <p>Java class for Block complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Block">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BlockDetails" type="{http://www.ws.lgd.pes.nic.in}LandDetails"/>
 *         &lt;element name="Villages" type="{http://www.ws.lgd.pes.nic.in}Villages" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Block", propOrder = {
    "blockDetails",
    "villages"
})
public class Block { // NO_UCD (use default)

    @XmlElement(name = "BlockDetails", required = true)
    private LandDetails blockDetails;
    @XmlElement(name = "Villages")
    private Villages villages;

    /**
     * Gets the value of the blockDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LandDetails }
     *     
     */
    public LandDetails getBlockDetails() {
        return blockDetails;
    }

    /**
     * Sets the value of the blockDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandDetails }
     *     
     */
    public void setBlockDetails(LandDetails value) {
        this.blockDetails = value;
    }

    /**
     * Gets the value of the villages property.
     * 
     * @return
     *     possible object is
     *     {@link Villages }
     *     
     */
    public Villages getVillages() {
        return villages;
    }

    /**
     * Sets the value of the villages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Villages }
     *     
     */
    public void setVillages(Villages value) {
        this.villages = value;
    }

}
