//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type will provide Entire Heirarchy of a particular District
 *             
 * 
 * <p>Java class for District complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="District">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DistrictDetails" type="{http://www.ws.lgd.pes.nic.in}LandDetails"/>
 *         &lt;element name="Subdistricts" type="{http://www.ws.lgd.pes.nic.in}Subdistricts" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Blocks" type="{http://www.ws.lgd.pes.nic.in}Blocks" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "District", propOrder = {
    "districtDetails",
    "subdistricts",
    "blocks"
})
public class District {

    @XmlElement(name = "DistrictDetails", required = true)
    private LandDetails districtDetails;
    @XmlElement(name = "Subdistricts")
    private List<Subdistricts> subdistricts;
    @XmlElement(name = "Blocks")
    private List<Blocks> blocks;

    /**
     * Gets the value of the districtDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LandDetails }
     *     
     */
    public LandDetails getDistrictDetails() {
        return districtDetails;
    }

    /**
     * Sets the value of the districtDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandDetails }
     *     
     */
    public void setDistrictDetails(LandDetails value) {
        this.districtDetails = value;
    }

    /**
     * Gets the value of the subdistricts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subdistricts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubdistricts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subdistricts }
     * 
     * 
     */
    public List<Subdistricts> getSubdistricts() {
        if (subdistricts == null) {
            subdistricts = new ArrayList<Subdistricts>();
        }
        return this.subdistricts;
    }

    /**
     * Gets the value of the blocks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blocks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlocks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Blocks }
     * 
     * 
     */
    public List<Blocks> getBlocks() {
        if (blocks == null) {
            blocks = new ArrayList<Blocks>();
        }
        return this.blocks;
    }

}
