//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type will provide Entire Heirarchy of a particular Land Region e.g
 *                 STATES
 *                 DISTRICTS
 *                 SUBDISTRICTS
 *                 BLOCKS
 *                 VILLAGES
 *             
 * 
 * <p>Java class for EntireLandRegion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntireLandRegion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="States" type="{http://www.ws.lgd.pes.nic.in}States"/>
 *           &lt;element name="Districts" type="{http://www.ws.lgd.pes.nic.in}Districts"/>
 *           &lt;element name="Subdistricts" type="{http://www.ws.lgd.pes.nic.in}Subdistricts"/>
 *           &lt;element name="Blocks" type="{http://www.ws.lgd.pes.nic.in}Blocks"/>
 *           &lt;element name="Villages" type="{http://www.ws.lgd.pes.nic.in}Villages"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntireLandRegion", propOrder = {
    "states",
    "districts",
    "subdistricts",
    "blocks",
    "villages"
})
public class EntireLandRegion { // NO_UCD (use default)

    @XmlElement(name = "States")
    private States states;
    @XmlElement(name = "Districts")
    private Districts districts;
    @XmlElement(name = "Subdistricts")
    private Subdistricts subdistricts;
    @XmlElement(name = "Blocks")
    private Blocks blocks;
    @XmlElement(name = "Villages")
    private Villages villages;

    /**
     * Gets the value of the states property.
     * 
     * @return
     *     possible object is
     *     {@link States }
     *     
     */
    public States getStates() {
        return states;
    }

    /**
     * Sets the value of the states property.
     * 
     * @param value
     *     allowed object is
     *     {@link States }
     *     
     */
    public void setStates(States value) {
        this.states = value;
    }

    /**
     * Gets the value of the districts property.
     * 
     * @return
     *     possible object is
     *     {@link Districts }
     *     
     */
    public Districts getDistricts() {
        return districts;
    }

    /**
     * Sets the value of the districts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Districts }
     *     
     */
    public void setDistricts(Districts value) {
        this.districts = value;
    }

    /**
     * Gets the value of the subdistricts property.
     * 
     * @return
     *     possible object is
     *     {@link Subdistricts }
     *     
     */
    public Subdistricts getSubdistricts() {
        return subdistricts;
    }

    /**
     * Sets the value of the subdistricts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subdistricts }
     *     
     */
    public void setSubdistricts(Subdistricts value) {
        this.subdistricts = value;
    }

    /**
     * Gets the value of the blocks property.
     * 
     * @return
     *     possible object is
     *     {@link Blocks }
     *     
     */
    public Blocks getBlocks() {
        return blocks;
    }

    /**
     * Sets the value of the blocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blocks }
     *     
     */
    public void setBlocks(Blocks value) {
        this.blocks = value;
    }

    /**
     * Gets the value of the villages property.
     * 
     * @return
     *     possible object is
     *     {@link Villages }
     *     
     */
    public Villages getVillages() {
        return villages;
    }

    /**
     * Sets the value of the villages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Villages }
     *     
     */
    public void setVillages(Villages value) {
        this.villages = value;
    }

}
