//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 GIS Information for "THIS" Land Region
 *             
 * 
 * <p>Java class for GISInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GISInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="MapURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="GISNodes" type="{http://www.ws.lgd.pes.nic.in}GISNodes"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GISInformation", propOrder = {
    "mapURL",
    "gisNodes"
})
public class GISInformation {

    @XmlElement(name = "MapURL")
    private String mapURL;
    @XmlElement(name = "GISNodes")
    private GISNodes gisNodes;

    /**
     * Gets the value of the mapURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapURL() {
        return mapURL;
    }

    /**
     * Sets the value of the mapURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapURL(String value) {
        this.mapURL = value;
    }

    /**
     * Gets the value of the gisNodes property.
     * 
     * @return
     *     possible object is
     *     {@link GISNodes }
     *     
     */
    public GISNodes getGISNodes() {
        return gisNodes;
    }

    /**
     * Sets the value of the gisNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link GISNodes }
     *     
     */
    public void setGISNodes(GISNodes value) {
        this.gisNodes = value;
    }

}
