//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 05:27:49 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvalidateVillageForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvalidateVillageForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceSubdistrict" type="{http://www.ws.lgd.pes.nic.in}District"/>
 *         &lt;element name="DestinationSubdistrict" type="{http://www.ws.lgd.pes.nic.in}Subdistrict"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvalidateVillageForm", propOrder = {
    "sourceSubdistrict",
    "destinationSubdistrict"
})
public class InvalidateVillageForm {

    @XmlElement(name = "SourceSubdistrict", required = true)
    private District sourceSubdistrict;
    @XmlElement(name = "DestinationSubdistrict")
    private Subdistrict destinationSubdistrict;

    /**
     * Gets the value of the sourceSubdistrict property.
     * 
     * @return
     *     possible object is
     *     {@link District }
     *     
     */
    public District getSourceSubdistrict() {
        return sourceSubdistrict;
    }

    /**
     * Sets the value of the sourceSubdistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link District }
     *     
     */
    public void setSourceSubdistrict(District value) {
        this.sourceSubdistrict = value;
    }

    /**
     * Gets the value of the destinationSubdistrict property.
     * 
     * @return
     *     possible object is
     *     {@link Subdistrict }
     *     
     */
    public Subdistrict getDestinationSubdistrict() {
        return destinationSubdistrict;
    }

    /**
     * Sets the value of the destinationSubdistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subdistrict }
     *     
     */
    public void setDestinationSubdistrict(Subdistrict value) {
        this.destinationSubdistrict = value;
    }

}
