//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 05:27:49 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvalidateDistrictForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvalidateDistrictForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceDistrict" type="{http://www.ws.lgd.pes.nic.in}District"/>
 *         &lt;element name="DestinationDistricts" type="{http://www.ws.lgd.pes.nic.in}Districts"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvalidateDistrictForm", propOrder = {
    "sourceDistrict",
    "destinationDistricts"
})
public class InvalidateDistrictForm { // NO_UCD (use default)

    @XmlElement(name = "SourceDistrict", required = true)
    private District sourceDistrict;
    @XmlElement(name = "DestinationDistricts", required = true)
    private Districts destinationDistricts;

    /**
     * Gets the value of the sourceDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link District }
     *     
     */
    public District getSourceDistrict() {
        return sourceDistrict;
    }

    /**
     * Sets the value of the sourceDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link District }
     *     
     */
    public void setSourceDistrict(District value) {
        this.sourceDistrict = value;
    }

    /**
     * Gets the value of the destinationDistricts property.
     * 
     * @return
     *     possible object is
     *     {@link Districts }
     *     
     */
    public Districts getDestinationDistricts() {
        return destinationDistricts;
    }

    /**
     * Sets the value of the destinationDistricts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Districts }
     *     
     */
    public void setDestinationDistricts(Districts value) {
        this.destinationDistricts = value;
    }

}
