//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Each Land Region is composed of A LandRegionType (List of Land Regions)
 *                 as well as Unique ID for that particular type of Land
 *             
 * 
 * <p>Java class for LandRegion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LandRegion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LandRegionType" type="{http://www.ws.lgd.pes.nic.in}LandRegionTypes"/>
 *         &lt;element name="LandRegionDetails" type="{http://www.ws.lgd.pes.nic.in}LandRegionDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LandRegion", propOrder = {
    "landRegionType",
    "landRegionDetails"
})
public class LandRegion { // NO_UCD (use default)

    @XmlElement(name = "LandRegionType", required = true)
    private LandRegionTypes landRegionType;
    @XmlElement(name = "LandRegionDetails")
    private LandRegionDetails landRegionDetails;

    /**
     * Gets the value of the landRegionType property.
     * 
     * @return
     *     possible object is
     *     {@link LandRegionTypes }
     *     
     */
    public LandRegionTypes getLandRegionType() {
        return landRegionType;
    }

    /**
     * Sets the value of the landRegionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandRegionTypes }
     *     
     */
    public void setLandRegionType(LandRegionTypes value) {
        this.landRegionType = value;
    }

    /**
     * Gets the value of the landRegionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LandRegionDetails }
     *     
     */
    public LandRegionDetails getLandRegionDetails() {
        return landRegionDetails;
    }

    /**
     * Sets the value of the landRegionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandRegionDetails }
     *     
     */
    public void setLandRegionDetails(LandRegionDetails value) {
        this.landRegionDetails = value;
    }

}
