//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Details of "THIS" Land Region
 *             
 * 
 * <p>Java class for LandDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LandDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AliasEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AliasLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Parents" type="{http://www.ws.lgd.pes.nic.in}Parents" minOccurs="0"/>
 *         &lt;element name="SSCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Census2001Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Census2011Code" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="GovernmentOrderDetails" type="{http://www.ws.lgd.pes.nic.in}GovernmentOrderDetails" minOccurs="0"/>
 *         &lt;element name="GISInformation" type="{http://www.ws.lgd.pes.nic.in}GISInformation" minOccurs="0"/>
 *         &lt;element name="SurveyNumbers" type="{http://www.ws.lgd.pes.nic.in}SurveyNumbers" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LandDetails", propOrder = {
    "code",
    "version",
    "nameEnglish",
    "nameLocal",
    "shortName",
    "aliasEnglish",
    "aliasLocal",
    "parents",
    "ssCode",
    "census2001Code",
    "census2011Code",
    "governmentOrderDetails",
    "gisInformation",
    "surveyNumbers"
})
public class LandDetails {

    @XmlElement(name = "Code")
    private Integer code;
    @XmlElement(name = "Version")
    private Integer version;
    @XmlElement(name = "NameEnglish")
    private String nameEnglish;
    @XmlElement(name = "NameLocal")
    private String nameLocal;
    @XmlElement(name = "ShortName")
    private String shortName;
    @XmlElement(name = "AliasEnglish")
    private String aliasEnglish;
    @XmlElement(name = "AliasLocal")
    private String aliasLocal;
    @XmlElement(name = "Parents")
    private Parents parents;
    @XmlElement(name = "SSCode")
    private String ssCode;
    @XmlElement(name = "Census2001Code")
    private String census2001Code;
    @XmlElement(name = "Census2011Code")
    private String census2011Code;
    @XmlElement(name = "GovernmentOrderDetails")
    private GovernmentOrderDetails governmentOrderDetails;
    @XmlElement(name = "GISInformation")
    private GISInformation gisInformation;
    @XmlElement(name = "SurveyNumbers")
    private SurveyNumbers surveyNumbers;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCode(Integer value) {
        this.code = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }

    /**
     * Gets the value of the nameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEnglish() {
        return nameEnglish;
    }

    /**
     * Sets the value of the nameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEnglish(String value) {
        this.nameEnglish = value;
    }

    /**
     * Gets the value of the nameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLocal() {
        return nameLocal;
    }

    /**
     * Sets the value of the nameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLocal(String value) {
        this.nameLocal = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the aliasEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasEnglish() {
        return aliasEnglish;
    }

    /**
     * Sets the value of the aliasEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasEnglish(String value) {
        this.aliasEnglish = value;
    }

    /**
     * Gets the value of the aliasLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasLocal() {
        return aliasLocal;
    }

    /**
     * Sets the value of the aliasLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasLocal(String value) {
        this.aliasLocal = value;
    }

    /**
     * Gets the value of the parents property.
     * 
     * @return
     *     possible object is
     *     {@link Parents }
     *     
     */
    public Parents getParents() {
        return parents;
    }

    /**
     * Sets the value of the parents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parents }
     *     
     */
    public void setParents(Parents value) {
        this.parents = value;
    }

    /**
     * Gets the value of the ssCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSCode() {
        return ssCode;
    }

    /**
     * Sets the value of the ssCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSCode(String value) {
        this.ssCode = value;
    }

    /**
     * Gets the value of the census2001Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensus2001Code() {
        return census2001Code;
    }

    /**
     * Sets the value of the census2001Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensus2001Code(String value) {
        this.census2001Code = value;
    }

    /**
     * Gets the value of the census2011Code property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getCensus2011Code() {
        return census2011Code;
    }

    /**
     * Sets the value of the census2011Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCensus2011Code(String value) {
        this.census2011Code = value;
    }

    /**
     * Gets the value of the governmentOrderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public GovernmentOrderDetails getGovernmentOrderDetails() {
        return governmentOrderDetails;
    }

    /**
     * Sets the value of the governmentOrderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public void setGovernmentOrderDetails(GovernmentOrderDetails value) {
        this.governmentOrderDetails = value;
    }

    /**
     * Gets the value of the gisInformation property.
     * 
     * @return
     *     possible object is
     *     {@link GISInformation }
     *     
     */
    public GISInformation getGISInformation() {
        return gisInformation;
    }

    /**
     * Sets the value of the gisInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GISInformation }
     *     
     */
    public void setGISInformation(GISInformation value) {
        this.gisInformation = value;
    }

    /**
     * Gets the value of the surveyNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link SurveyNumbers }
     *     
     */
    public SurveyNumbers getSurveyNumbers() {
        return surveyNumbers;
    }

    /**
     * Sets the value of the surveyNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurveyNumbers }
     *     
     */
    public void setSurveyNumbers(SurveyNumbers value) {
        this.surveyNumbers = value;
    }

}
