//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Details of "THIS" particular Land Region
 *             
 * 
 * <p>Java class for LandRegionDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LandRegionDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NameEnglish" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AliasEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AliasLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Census2001Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Census2011Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GISInformation" type="{http://www.ws.lgd.pes.nic.in}GISInformation" minOccurs="0"/>
 *         &lt;element name="GovernmentOrder" type="{http://www.ws.lgd.pes.nic.in}GovernmentOrderDetails" minOccurs="0"/>
 *         &lt;element name="KeepsExistingName" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NewNameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NewNameLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsInvalidated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LandRegionDetails", propOrder = {
    "code",
    "nameEnglish",
    "nameLocal",
    "shortName",
    "aliasEnglish",
    "aliasLocal",
    "version",
    "census2001Code",
    "census2011Code",
    "gisInformation",
    "governmentOrder",
    "keepsExistingName",
    "newNameEnglish",
    "newNameLocal",
    "isInvalidated"
})
public class LandRegionDetails { // NO_UCD (use default)

    @XmlElement(name = "Code")
    private int code;
    @XmlElement(name = "NameEnglish", required = true)
    private String nameEnglish;
    @XmlElement(name = "NameLocal")
    private String nameLocal;
    @XmlElement(name = "ShortName")
    private String shortName;
    @XmlElement(name = "AliasEnglish")
    private String aliasEnglish;
    @XmlElement(name = "AliasLocal")
    private String aliasLocal;
    @XmlElement(name = "Version")
    private int version;
    @XmlElement(name = "Census2001Code")
    private String census2001Code;
    @XmlElement(name = "Census2011Code")
    private String census2011Code;
    @XmlElement(name = "GISInformation")
    private GISInformation gisInformation;
    @XmlElement(name = "GovernmentOrder")
    private GovernmentOrderDetails governmentOrder;
    @XmlElement(name = "KeepsExistingName", defaultValue = "true")
    private Boolean keepsExistingName;
    @XmlElement(name = "NewNameEnglish")
    private String newNameEnglish;
    @XmlElement(name = "NewNameLocal")
    private String newNameLocal;
    @XmlElement(name = "IsInvalidated", defaultValue = "false")
    private Boolean isInvalidated;

    /**
     * Gets the value of the code property.
     * 
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCode(int value) {
        this.code = value;
    }

    /**
     * Gets the value of the nameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEnglish() {
        return nameEnglish;
    }

    /**
     * Sets the value of the nameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEnglish(String value) {
        this.nameEnglish = value;
    }

    /**
     * Gets the value of the nameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLocal() {
        return nameLocal;
    }

    /**
     * Sets the value of the nameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLocal(String value) {
        this.nameLocal = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the aliasEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasEnglish() {
        return aliasEnglish;
    }

    /**
     * Sets the value of the aliasEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasEnglish(String value) {
        this.aliasEnglish = value;
    }

    /**
     * Gets the value of the aliasLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasLocal() {
        return aliasLocal;
    }

    /**
     * Sets the value of the aliasLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasLocal(String value) {
        this.aliasLocal = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }

    /**
     * Gets the value of the census2001Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensus2001Code() {
        return census2001Code;
    }

    /**
     * Sets the value of the census2001Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensus2001Code(String value) {
        this.census2001Code = value;
    }

    /**
     * Gets the value of the census2011Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensus2011Code() {
        return census2011Code;
    }

    /**
     * Sets the value of the census2011Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensus2011Code(String value) {
        this.census2011Code = value;
    }

    /**
     * Gets the value of the gisInformation property.
     * 
     * @return
     *     possible object is
     *     {@link GISInformation }
     *     
     */
    public GISInformation getGISInformation() {
        return gisInformation;
    }

    /**
     * Sets the value of the gisInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GISInformation }
     *     
     */
    public void setGISInformation(GISInformation value) {
        this.gisInformation = value;
    }

    /**
     * Gets the value of the governmentOrder property.
     * 
     * @return
     *     possible object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public GovernmentOrderDetails getGovernmentOrder() {
        return governmentOrder;
    }

    /**
     * Sets the value of the governmentOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public void setGovernmentOrder(GovernmentOrderDetails value) {
        this.governmentOrder = value;
    }

    /**
     * Gets the value of the keepsExistingName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeepsExistingName() {
        return keepsExistingName;
    }

    /**
     * Sets the value of the keepsExistingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeepsExistingName(Boolean value) {
        this.keepsExistingName = value;
    }

    /**
     * Gets the value of the newNameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewNameEnglish() {
        return newNameEnglish;
    }

    /**
     * Sets the value of the newNameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewNameEnglish(String value) {
        this.newNameEnglish = value;
    }

    /**
     * Gets the value of the newNameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewNameLocal() {
        return newNameLocal;
    }

    /**
     * Sets the value of the newNameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewNameLocal(String value) {
        this.newNameLocal = value;
    }

    /**
     * Gets the value of the isInvalidated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInvalidated() {
        return isInvalidated;
    }

    /**
     * Sets the value of the isInvalidated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInvalidated(Boolean value) {
        this.isInvalidated = value;
    }

}
