//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type will provide local body name in both English AND/OR Local language
 *             
 * 
 * <p>Java class for LocalBodyName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocalBodyName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocalBodyName" type="{http://www.ws.lgd.pes.nic.in}EntityName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalBodyName", propOrder = {
    "localBodyName"
})
public class LocalBodyName { // NO_UCD (use default)

    @XmlElement(name = "LocalBodyName", required = true)
    private EntityName localBodyName;

    /**
     * Gets the value of the localBodyName property.
     * 
     * @return
     *     possible object is
     *     {@link EntityName }
     *     
     */
    public EntityName getLocalBodyName() {
        return localBodyName;
    }

    /**
     * Sets the value of the localBodyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityName }
     *     
     */
    public void setLocalBodyName(EntityName value) {
        this.localBodyName = value;
    }

}
