//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type will provide details of Nomenclature of a particular Local Body Type for a particular State
 *             
 * 
 * <p>Java class for Nomenclature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Nomenclature">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NomenclatureEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NomenclatureLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nomenclature", propOrder = {
    "nomenclatureEnglish",
    "nomenclatureLocal"
})
public class Nomenclature { // NO_UCD (use default)

    @XmlElement(name = "NomenclatureEnglish")
    private String nomenclatureEnglish;
    @XmlElement(name = "NomenclatureLocal")
    private String nomenclatureLocal;

    /**
     * Gets the value of the nomenclatureEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomenclatureEnglish() {
        return nomenclatureEnglish;
    }

    /**
     * Sets the value of the nomenclatureEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomenclatureEnglish(String value) {
        this.nomenclatureEnglish = value;
    }

    /**
     * Gets the value of the nomenclatureLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomenclatureLocal() {
        return nomenclatureLocal;
    }

    /**
     * Sets the value of the nomenclatureLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomenclatureLocal(String value) {
        this.nomenclatureLocal = value;
    }

}
