//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type will provide List of Nomenclature of Local Body Types for a particular State and Category Wise
 *             
 * 
 * <p>Java class for NomenclatureOfLBTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NomenclatureOfLBTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StateCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Category" type="{http://www.ws.lgd.pes.nic.in}Category"/>
 *         &lt;element name="Nomenclatures" type="{http://www.ws.lgd.pes.nic.in}Nomenclatures"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NomenclatureOfLBTypes", propOrder = {
    "stateCode",
    "category",
    "nomenclatures"
})
public class NomenclatureOfLBTypes { // NO_UCD (use default)

    @XmlElement(name = "StateCode")
    private int stateCode;
    @XmlElement(name = "Category", required = true)
    private Category category;
    @XmlElement(name = "Nomenclatures", required = true)
    private Nomenclatures nomenclatures;

    /**
     * Gets the value of the stateCode property.
     * 
     */
    public int getStateCode() {
        return stateCode;
    }

    /**
     * Sets the value of the stateCode property.
     * 
     */
    public void setStateCode(int value) {
        this.stateCode = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the nomenclatures property.
     * 
     * @return
     *     possible object is
     *     {@link Nomenclatures }
     *     
     */
    public Nomenclatures getNomenclatures() {
        return nomenclatures;
    }

    /**
     * Sets the value of the nomenclatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomenclatures }
     *     
     */
    public void setNomenclatures(Nomenclatures value) {
        this.nomenclatures = value;
    }

}
