//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrganizationLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganizationLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LandRegionCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="LandRegionVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="LandRegionType" type="{http://www.ws.lgd.pes.nic.in}LandRegionTypes"/>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationLocation", propOrder = {
    "landRegionCode",
    "landRegionVersion",
    "landRegionType",
    "address",
    "phoneNo"
})
public class OrganizationLocation { // NO_UCD (use default)

    @XmlElement(name = "LandRegionCode")
    private Integer landRegionCode;
    @XmlElement(name = "LandRegionVersion")
    private Integer landRegionVersion;
    @XmlElement(name = "LandRegionType", required = true)
    private LandRegionTypes landRegionType;
    @XmlElement(name = "Address")
    private String address;
    @XmlElement(name = "PhoneNo")
    private String phoneNo;

    /**
     * Gets the value of the landRegionCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLandRegionCode() {
        return landRegionCode;
    }

    /**
     * Sets the value of the landRegionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLandRegionCode(Integer value) {
        this.landRegionCode = value;
    }

    /**
     * Gets the value of the landRegionVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLandRegionVersion() {
        return landRegionVersion;
    }

    /**
     * Sets the value of the landRegionVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLandRegionVersion(Integer value) {
        this.landRegionVersion = value;
    }

    /**
     * Gets the value of the landRegionType property.
     * 
     * @return
     *     possible object is
     *     {@link LandRegionTypes }
     *     
     */
    public LandRegionTypes getLandRegionType() {
        return landRegionType;
    }

    /**
     * Sets the value of the landRegionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandRegionTypes }
     *     
     */
    public void setLandRegionType(LandRegionTypes value) {
        this.landRegionType = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the phoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * Sets the value of the phoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNo(String value) {
        this.phoneNo = value;
    }

}
