//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Organization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrganizationCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="OrganizationVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrganizationTypeCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="LocalGovTypeCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="OrganizationLocations" type="{http://www.ws.lgd.pes.nic.in}OrganizationLocations" minOccurs="0"/>
 *         &lt;element name="GovernmentOrderDetails" type="{http://www.ws.lgd.pes.nic.in}GovernmentOrderDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organization", propOrder = {
    "organizationCode",
    "organizationVersion",
    "nameEnglish",
    "nameLocal",
    "organizationTypeCode",
    "localGovTypeCode",
    "organizationLocations",
    "governmentOrderDetails"
})
public class Organization { // NO_UCD (use default)

    @XmlElement(name = "OrganizationCode")
    private Integer organizationCode;
    @XmlElement(name = "OrganizationVersion")
    private Integer organizationVersion;
    @XmlElement(name = "NameEnglish")
    private String nameEnglish;
    @XmlElement(name = "NameLocal")
    private String nameLocal;
    @XmlElement(name = "OrganizationTypeCode")
    private Integer organizationTypeCode;
    @XmlElement(name = "LocalGovTypeCode")
    private Integer localGovTypeCode;
    @XmlElement(name = "OrganizationLocations")
    private OrganizationLocations organizationLocations;
    @XmlElement(name = "GovernmentOrderDetails")
    private GovernmentOrderDetails governmentOrderDetails;

    /**
     * Gets the value of the organizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrganizationCode() {
        return organizationCode;
    }

    /**
     * Sets the value of the organizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrganizationCode(Integer value) {
        this.organizationCode = value;
    }

    /**
     * Gets the value of the organizationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrganizationVersion() {
        return organizationVersion;
    }

    /**
     * Sets the value of the organizationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrganizationVersion(Integer value) {
        this.organizationVersion = value;
    }

    /**
     * Gets the value of the nameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEnglish() {
        return nameEnglish;
    }

    /**
     * Sets the value of the nameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEnglish(String value) {
        this.nameEnglish = value;
    }

    /**
     * Gets the value of the nameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLocal() {
        return nameLocal;
    }

    /**
     * Sets the value of the nameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLocal(String value) {
        this.nameLocal = value;
    }

    /**
     * Gets the value of the organizationTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrganizationTypeCode() {
        return organizationTypeCode;
    }

    /**
     * Sets the value of the organizationTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrganizationTypeCode(Integer value) {
        this.organizationTypeCode = value;
    }

    /**
     * Gets the value of the localGovTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLocalGovTypeCode() {
        return localGovTypeCode;
    }

    /**
     * Sets the value of the localGovTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLocalGovTypeCode(Integer value) {
        this.localGovTypeCode = value;
    }

    /**
     * Gets the value of the organizationLocations property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationLocations }
     *     
     */
    public OrganizationLocations getOrganizationLocations() {
        return organizationLocations;
    }

    /**
     * Sets the value of the organizationLocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationLocations }
     *     
     */
    public void setOrganizationLocations(OrganizationLocations value) {
        this.organizationLocations = value;
    }

    /**
     * Gets the value of the governmentOrderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public GovernmentOrderDetails getGovernmentOrderDetails() {
        return governmentOrderDetails;
    }

    /**
     * Sets the value of the governmentOrderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GovernmentOrderDetails }
     *     
     */
    public void setGovernmentOrderDetails(GovernmentOrderDetails value) {
        this.governmentOrderDetails = value;
    }

}
