//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Details of "THIS" Land Region's Parent
 *             
 * 
 * <p>Java class for Parent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParentCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ParentVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ParentNameEnglish" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parent", propOrder = {
    "parentCode",
    "parentVersion",
    "parentNameEnglish"
})
public class Parent {

    @XmlElement(name = "ParentCode")
    private int parentCode;
    @XmlElement(name = "ParentVersion")
    private Integer parentVersion;
    @XmlElement(name = "ParentNameEnglish")
    private String parentNameEnglish;

    /**
     * Gets the value of the parentCode property.
     * 
     */
    public int getParentCode() {
        return parentCode;
    }

    /**
     * Sets the value of the parentCode property.
     * 
     */
    public void setParentCode(int value) {
        this.parentCode = value;
    }

    /**
     * Gets the value of the parentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParentVersion() {
        return parentVersion;
    }

    /**
     * Sets the value of the parentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParentVersion(Integer value) {
        this.parentVersion = value;
    }

    /**
     * Gets the value of the parentNameEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentNameEnglish() {
        return parentNameEnglish;
    }

    /**
     * Sets the value of the parentNameEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentNameEnglish(String value) {
        this.parentNameEnglish = value;
    }

}
