//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.08 at 01:51:11 PM IST 
//


package in.nic.pes.lgd.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type will provide Entire Heirarchy of a VILLAGES in a SUBDISTRICT/BLOCK for Village UI Forms
 *             
 * 
 * <p>Java class for VillageForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VillageForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LandDetails" type="{http://www.ws.lgd.pes.nic.in}LandDetails"/>
 *         &lt;element name="ContributingVillages" type="{http://www.ws.lgd.pes.nic.in}Villages" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VillageForm", propOrder = {
    "landDetails",
    "contributingVillages"
})
public class VillageForm {

    @XmlElement(name = "LandDetails", required = true)
    private LandDetails landDetails;
    @XmlElement(name = "ContributingVillages")
    private Villages contributingVillages;

    /**
     * Gets the value of the landDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LandDetails }
     *     
     */
    public LandDetails getLandDetails() {
        return landDetails;
    }

    /**
     * Sets the value of the landDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandDetails }
     *     
     */
    public void setLandDetails(LandDetails value) {
        this.landDetails = value;
    }

    /**
     * Gets the value of the contributingVillages property.
     * 
     * @return
     *     possible object is
     *     {@link Villages }
     *     
     */
    public Villages getContributingVillages() {
        return contributingVillages;
    }

    /**
     * Sets the value of the contributingVillages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Villages }
     *     
     */
    public void setContributingVillages(Villages value) {
        this.contributingVillages = value;
    }

}
