package in.nic.pes.lgd.common;

import java.util.EnumSet;

public enum MenuDisableConstant
{
  ENTITY_STATE_LEVEL("S"),  ENTITY_DISTRICT_LEVEL("D"),  LR_CREATE_STATE(
  

    "Create State"),  LR_MANAGE_STATE("Manage State"),  LR_CREATE_DISTRICT("Create District"),  LR_MANAGE_DISTRICT("Manage District"),  LR_CREATE_SUB_DISTRICT("Create Subdistrict"),  LR_MANAGE_SUB_DISTRICT("Manage Subdistrict"),  LR_CREATE_VILLAGE("Create Village"),  LR_MANAGE_VILLAGE("Manage Village"),  LR_INVALIDATE_VILLAGE_MERGE_ULB("Invalidate Village (Merge ULB)"),  LR_SHIFT_DISTRICT("Shift District"),  LR_SHIFT_SUB_DISTRICT("Shift Subdistrict"),  LR_SHIFT_VILLAGE_BTN_SUBDST("Shift Village Between Subdistricts"),  LR_INVALID_DISTRICT("Invalidate District"),  LR_INVALID_SUB_DISTRICT("Invalidate Subdistrict"),  LR_INVALID_VILLAGE("Invalidate Village"),  LB_PRI_CREATE(
  

    "Create PRI LocalBody"),  LB_PRI_MANAGE("Manage PRI LocalBody"),  LB_PRI_CREATE_ER_DESIGNATION("Create ER Designation (Panchayat)"),  LB_PRI_CREATE_OFFICIAL_DESIGNATION("Create Official Designation (Panchayat)"),  LB_PRI_CREATE_OFFICIAL_REPORTING("Create Official Reporting (Panchayat)"),  LB_PRI_REORDER_ER_DESIGNATION("Reorder ER Designation (Panchyat)"),  LB_PRI_REORDER_OFFICIAL_DESIGNATION("Reorder Official Designation (Panchyat)"),  LB_PRI_MARK_PESA("Mark Pesa Panchayats"),  LB_PRI_INVALIDATE("Invalidate PRI LocalBody"),  LB_PRI_CONVERT_RLB("Convert RLB to ULB"),  LB_TRADITIONAL_CREATE(
  

    "Create Traditional LocalBody"),  LB_TRADITIONAL_MANAGE("Manage Traditional LocalBody"),  LB_TRADITIONAL_CREATE_ER_DESIGNATION("Create ER Designation (Traditional)"),  LB_TRADITIONAL_CREATE_OFFICIAL_DESIGNATION("Create Official Designation (Traditional)"),  LB_TRADITIONAL_CREATE_OFFICIAL_REPORTING("Create Official Reporting (Traditional)"),  LB_TRADITIONAL_REORDER_ER_DESIGNATION("Reorder ER Designation (Traditional)"),  LB_TRADITIONAL_REORDER_OFFICIAL_DESIGNATION("Reorder Official Designation (Traditional)"),  LB_TRADITIONAL_INVALIDATE("Invalidate Traditional LocalBody"),  LB_TRADITIONAL_CONVERT_TLB("Convert TLB to ULB"),  LB_URBAN_CREATE(
  

    "Create Urban LocalBody"),  LB_URBAN_MANAGE("Manage Urban LocalBody"),  LB_URBAN_CREATE_ER_DESIGNATION("Create ER Designation (Urban)"),  LB_URBAN_CREATE_OFFICIAL_DESIGNATION("Create Official Designation (Urban)"),  LB_URBAN_CREATE_OFFICIAL_REPORTING("Create Official Reporting (Urban)"),  LB_URBAN_REORDER_ER_DESIGNATION("Reorder ER Designation (Urban)"),  LB_URBAN_REORDER_OFFICIAL_DESIGNATION("Reorder Official Designation (Urban)"),  LB_URBAN_INVALIDATE("Invalidate Urban LocalBody"),  LB_URBAN_CONVERT_RLB("Convert RLB to ULB"),  LB_URBAN_CONVERT_TLB("Convert TLB to ULB")
  
  
  ,SIFT_VILLAGE_BETWEEN_BLOCK("Shift Village Between Blocks") , INVALIDATE_BLOCK("Invalidate Block") , CREATE_BLOCK("Create Block") ,MANAGE_BLOCK("Manage Block") , 
  MAP_BLOCKWISE_VILLAGE("Map Block wise Villages") , CGO_BLOCK("Configure Government Order(Block)") , UOSC_BLOCK("Update Other Standard Codes/Local Names(Block)") ,
  
	
	CONFIGURE_MAP("Configure Map (Constituency)"), CREATE_PARLIAMENT_CONSTITUENCY("Create Parliament Constituency"), CREATE_ASSEMBLY_CONST("Create Assembly Constituency"),
	MODIFY_PARLIAMENT_CONST("Modify Parliament Constituency"), MODIFY_ASSEMBLY_CONST("Modify Assembly Constituency"), 
	MAP_PARLIAMENT_CONST("Map Parliament Constituency"), CHANGE_NODAL_OFFICER_DETAILS("Change Nodal Officer Details"),
	
	LR_CONFIGURE_SYSTEM("Configure Government Order (Land Region)"),LR_UN_RESOLVED_ENTITY("Manage Un-Resolved Entities(Land Region)"),LR_MISCELLANEOUS( "Update Other Standard Codes/Local Names(Landregion)"),LR_GD_DATA_CONFIRMATION("Change Nodal Officer Details"),LR_REACTIVATE("Reactivate Village"),
	LR_MENU_CHANGEPASSWORD("menu.changepassword"),LR_MENU_CONFIGUREPESUSERACCOUNTS("menu.configurepesuseraccounts"),
	
    LB_CREATE_N_MANAGE_PRI_WARD("Create n Manage PRI Ward"),LB_PUBLISH_PRI_WARD_CHANGES("Publish PRI Ward Changes"),
   LB_ADD_N_MANAGE_PRI_WARD_COVERAGE("Add n Manage PRI Ward Coverage"),LB_PUBLISH_PRI_WARD_COVERAGE_CHANGES("Publish PRI Ward Coverage Changes"),LB_DEFINE_PANCHAYAT_LOCAL_GOVERNMENT_SETUP("Define Panchayat Local Government Setup"),
   LB_MANAGE_UN_RESOLVED_ENTITIES_PRI("Manage Un-Resolved Entities(PRI)"),LB_UPDATE_OTHER_STANDARD_CODES_LOCAL_NAMES_PANCHAYAT("Update Other Standard Codes/Local Names(Panchayat)"),
  LB_UPDATE_LOCAL_NAMES_OF_WARD_PANCHAYAT("Update Local Names of Ward(Panchayat)"),LB_UPDATE_GIS_BOUNDARIES_GRAM_PANCHAYAT("Update GIS Boundaries(Gram Panchayat)"),LB_CHANGE_NODAL_OFFICER_DETAILS("Change Nodal Officer Details"),
  LB_REACTIVATE_LOCALBODY("Reactivate LocalBody"),
  
 CREATE_N_MANAGE_PRI_WARD("Create n Manage PRI Ward"),PUBLISH_PRI_WARD_CHANGES("Publish PRI Ward Changes"),ADD_N_MANAGE_PRI_WARD_COVERAGE("Add n Manage PRI Ward Coverage"),PUBLISH_PRI_WARD_COVERAGE_CHANGES("Publish PRI Ward Coverage Changes"),DEFINE_PANCHAYAT_LOCAL_GOVERNMENT_SETUP("Define Panchayat Local Government Setup"),
 CREATE_ASSEMBLY_CONSTITUENCY("Create Assembly Constituency"),MAP_PARLIAMENT_CONSTITUENCY("Map Parliament Constituency"),
MODIFY_PARLIAMENT_CONSTITUENCY("Modify Parliament Constituency"),MODIFY_ASSEMBLY_CONSTITUENCY("Modify Assembly Constituency"),
MANAGE_UN_RESOLVED_ENTITIES_PRI("Manage Un-Resolved Entities(PRI)"),UPDATE_OTHER_STANDARD_CODES_LOCAL_NAMES_PANCHAYAT("Update Other Standard Codes/Local Names(Panchayat)"),
UPDATE_LOCAL_NAMES_OF_WARD_PANCHAYAT("Update Local Names of Ward(Panchayat)"),MARK_PESA_LAND_REGIONS("Mark Pesa Land Regions"),
UPDATE_GIS_BOUNDARIES_GRAM_PANCHAYAT("Update GIS Boundaries(Gram Panchayat)"),REACTIVATE_LOCALBODY("Reactivate LocalBody"),
LR_CONFIGURE_GOVERNMRNT_ORDER("Configure Governmrnt Order"),LR_CONFIGURE_MAP("Configure Map"),LR_MANAGE_UNRESOLVED_ENTITY("Manage unresolved entity"),LR_UPDATE_OTHER_STANDARD_CODE_LOCAL_NAME_CHANGE_NODAL_OFFICER_DETAILS("update other standard code / local name change nodal officer Details");

  
  private String value;
  
  private MenuDisableConstant() {}
  
  private MenuDisableConstant(String value)
  {
    this.value = value;
  }
  
  public String toString()
  {
    return this.value != null ? this.value : name();
  }
  
  public static EnumSet<MenuDisableConstant> stateLinks = EnumSet.of(LR_CREATE_STATE, new MenuDisableConstant[] { LR_MANAGE_STATE, LR_CREATE_DISTRICT, LR_MANAGE_DISTRICT, LR_CREATE_SUB_DISTRICT, 
    LR_MANAGE_SUB_DISTRICT, LR_CREATE_VILLAGE, LR_MANAGE_VILLAGE, LR_INVALIDATE_VILLAGE_MERGE_ULB, LR_SHIFT_DISTRICT, LR_SHIFT_SUB_DISTRICT, 
    LR_SHIFT_VILLAGE_BTN_SUBDST, LR_INVALID_DISTRICT, LR_INVALID_SUB_DISTRICT, LR_INVALID_VILLAGE,CREATE_N_MANAGE_PRI_WARD,PUBLISH_PRI_WARD_CHANGES,ADD_N_MANAGE_PRI_WARD_COVERAGE,PUBLISH_PRI_WARD_COVERAGE_CHANGES,DEFINE_PANCHAYAT_LOCAL_GOVERNMENT_SETUP,CREATE_PARLIAMENT_CONSTITUENCY,
    CREATE_PARLIAMENT_CONSTITUENCY,CREATE_ASSEMBLY_CONSTITUENCY,MAP_PARLIAMENT_CONSTITUENCY,MODIFY_PARLIAMENT_CONSTITUENCY,MODIFY_ASSEMBLY_CONSTITUENCY,MANAGE_UN_RESOLVED_ENTITIES_PRI,UPDATE_OTHER_STANDARD_CODES_LOCAL_NAMES_PANCHAYAT,
    UPDATE_LOCAL_NAMES_OF_WARD_PANCHAYAT,MARK_PESA_LAND_REGIONS,UPDATE_GIS_BOUNDARIES_GRAM_PANCHAYAT,CHANGE_NODAL_OFFICER_DETAILS,REACTIVATE_LOCALBODY,LR_CONFIGURE_GOVERNMRNT_ORDER,LR_CONFIGURE_MAP,LR_MANAGE_UNRESOLVED_ENTITY,LR_UPDATE_OTHER_STANDARD_CODE_LOCAL_NAME_CHANGE_NODAL_OFFICER_DETAILS });
  
  public static EnumSet<MenuDisableConstant> districtLinks = EnumSet.of(LR_CREATE_DISTRICT, new MenuDisableConstant[] { LR_MANAGE_DISTRICT, LR_CREATE_SUB_DISTRICT, LR_MANAGE_SUB_DISTRICT, 
    LR_CREATE_VILLAGE, LR_MANAGE_VILLAGE, LR_INVALIDATE_VILLAGE_MERGE_ULB, LR_SHIFT_DISTRICT, LR_SHIFT_SUB_DISTRICT, 
    LR_SHIFT_VILLAGE_BTN_SUBDST, LR_INVALID_DISTRICT, LR_INVALID_SUB_DISTRICT, LR_INVALID_VILLAGE ,LR_CONFIGURE_SYSTEM,LR_UN_RESOLVED_ENTITY,LR_MISCELLANEOUS,LR_GD_DATA_CONFIRMATION,LR_REACTIVATE,LR_MENU_CHANGEPASSWORD,LR_MENU_CONFIGUREPESUSERACCOUNTS });
  public static EnumSet<MenuDisableConstant> priLinks = EnumSet.of(LB_PRI_CREATE, new MenuDisableConstant[] { LB_PRI_MANAGE, LB_PRI_CREATE_ER_DESIGNATION, LB_PRI_CREATE_OFFICIAL_DESIGNATION, 
    LB_PRI_CREATE_OFFICIAL_REPORTING, LB_PRI_REORDER_ER_DESIGNATION, LB_PRI_REORDER_OFFICIAL_DESIGNATION, 
    LB_PRI_MARK_PESA, LB_PRI_INVALIDATE, LB_PRI_CONVERT_RLB,LB_CREATE_N_MANAGE_PRI_WARD,LB_PUBLISH_PRI_WARD_CHANGES,LB_ADD_N_MANAGE_PRI_WARD_COVERAGE,LB_PUBLISH_PRI_WARD_COVERAGE_CHANGES,LB_DEFINE_PANCHAYAT_LOCAL_GOVERNMENT_SETUP,LB_MANAGE_UN_RESOLVED_ENTITIES_PRI,LB_UPDATE_OTHER_STANDARD_CODES_LOCAL_NAMES_PANCHAYAT,LB_UPDATE_LOCAL_NAMES_OF_WARD_PANCHAYAT,LB_UPDATE_GIS_BOUNDARIES_GRAM_PANCHAYAT,LB_CHANGE_NODAL_OFFICER_DETAILS,LB_REACTIVATE_LOCALBODY });
  public static EnumSet<MenuDisableConstant> traditionalLinks = EnumSet.of(LB_TRADITIONAL_CREATE, new MenuDisableConstant[] { LB_TRADITIONAL_MANAGE, LB_TRADITIONAL_CREATE_ER_DESIGNATION, 
    LB_TRADITIONAL_CREATE_OFFICIAL_DESIGNATION, LB_TRADITIONAL_CREATE_OFFICIAL_REPORTING, LB_TRADITIONAL_REORDER_ER_DESIGNATION, 
    LB_TRADITIONAL_REORDER_OFFICIAL_DESIGNATION, LB_TRADITIONAL_INVALIDATE, LB_TRADITIONAL_CONVERT_TLB });
  public static EnumSet<MenuDisableConstant> urbanLinks = EnumSet.of(LB_URBAN_CREATE, new MenuDisableConstant[] { LB_URBAN_MANAGE, LB_URBAN_CREATE_ER_DESIGNATION, LB_URBAN_CREATE_OFFICIAL_DESIGNATION, 
    LB_URBAN_CREATE_OFFICIAL_REPORTING, LB_URBAN_REORDER_ER_DESIGNATION, LB_URBAN_REORDER_OFFICIAL_DESIGNATION, 
    LB_URBAN_INVALIDATE, LB_URBAN_CONVERT_RLB, LB_URBAN_CONVERT_TLB });
  
  public static EnumSet<MenuDisableConstant> blocklinks = EnumSet.of(SIFT_VILLAGE_BETWEEN_BLOCK, new MenuDisableConstant[] { INVALIDATE_BLOCK, CREATE_BLOCK, MANAGE_BLOCK, 
		  MAP_BLOCKWISE_VILLAGE, CGO_BLOCK, UOSC_BLOCK });
  
  public static EnumSet<MenuDisableConstant> constituencylinks = EnumSet.of(CONFIGURE_MAP, new MenuDisableConstant[] { CREATE_PARLIAMENT_CONSTITUENCY, CREATE_ASSEMBLY_CONST,
		  MODIFY_PARLIAMENT_CONST,  MODIFY_ASSEMBLY_CONST, MAP_PARLIAMENT_CONST, CHANGE_NODAL_OFFICER_DETAILS });
}
